### ISSUE TITLE
Check install-run process

### ISSUE THREAD

**Issue by LouiseABowler** [kochkinaelena/branchLSTM#1]
I'm starting with a clean installation on my computer - this issue is to document any changes that have to be made to the code, file organisation or documentation in order to get the Lasagne version of branchLSTM working.

**Comment by LouiseABowler** [comment]
1bebd4c introduces a .gitignore file and makes a couple of changes to preprocessing.py:

- The `punkt` NLTK data is downloaded and stored in the same directory as the code
- The method for loading the GoogleNews data has been updated (original was deprecated in an earlier version of gensim)

One remaining problem - preprocessing.py expects there to be a `replies` folder for each tweet. If this folder is empty, it isn't uploaded to GitHub. So we have two options:

- Ask the user to download the data directly from the SemEval-2017 website (which we already do for the GoogleNews data)
- Add a file to every subfolder in the `semeval2017-task8-dataset` directory to ensure that otherwise empty folders are still uploaded to GitHub

I'm inclined to go with the first option, but let me know if any opinions.

**Comment by kochkinaelena** [comment]
Yes, first option seems fine to me.

**Comment by LouiseABowler** [comment]
22f80eb942341cccaafa765b0e9f5496a5856489 introduces a requirements file for easy installation (a couple of follow-up commits got this working when not logged into GitHub).

bcf0ec720b54df3953a521fccc3709ff085c801c adds the option to perform a test tun of `outer.py` with unrealistic parameters values, and removes the SemEval-2017 datasets as discussed in the previous comments.

5d4ef035fb81dd094ef75fb3294cb6dfa8035da9 adds instructions for downloading the required datasets via the command line.

I've now got `preprocessing.py` and `outer.py` running on my main computer, laptop and an basic Ubuntu VM on Azure, and the `scorerA` script successfully analyses the output. Now onto the final task related to this issue - get the GPU version running and document how to do this.
